CREATE TABLE FOO
(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE BAR
(
    ID BIGINT PRIMARY KEY,
    FOO_ID BIGINT NOT NULL,

    CONSTRAINT BAR_FOO_FK FOREIGN KEY (FOO_ID) REFERENCES FOO (ID)
);

INSERT INTO FOO (ID, NAME) VALUES (1, 'one');
INSERT INTO BAR (ID, FOO_ID) VALUES (10, 1);

INSERT INTO FOO (ID, NAME) VALUES (2, 'two');
INSERT INTO BAR (ID, FOO_ID) VALUES (20, 2);
INSERT INTO BAR (ID, FOO_ID) VALUES (21, 2);
